//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccount
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public int Id { get; set; }
        public string ExecutionTime { get; set; }
        public string Saldo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
