//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccount
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankModelContainer : DbContext
    {
        public BankModelContainer()
            : base("name=BankModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> CustomerSet { get; set; }
        public virtual DbSet<Bank> BankSet { get; set; }
        public virtual DbSet<Account> AccountSet { get; set; }
        public virtual DbSet<CustomerAccount> CustomerAccountSet { get; set; }
        public virtual DbSet<TypCustomer> TypCustomerSet { get; set; }
        public virtual DbSet<TypeAccount> TypeAccountSet { get; set; }
        public virtual DbSet<Employees> EmployeesSet1 { get; set; }
        public virtual DbSet<Transaction> TransactionSet { get; set; }
        public virtual DbSet<AccountTransaction> AccountTransactionSet { get; set; }
        public virtual DbSet<Gender> GenderSet { get; set; }
        public virtual DbSet<Position> PositionSet { get; set; }
    }
}
