//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccount
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.TypeAccount = new HashSet<CustomerAccount>();
        }
    
        public int Id { get; set; }
        public string Addresse { get; set; }
        public string FirstName { get; set; }
        public string DateOfBirth { get; set; }
        public string LastName { get; set; }
        public string SVNumber { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAccount> TypeAccount { get; set; }
        public virtual TypCustomer TypCustomer { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
