//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccount
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string DateOfBirth { get; set; }
        public string LastName { get; set; }
        public string SVNumber { get; set; }
        public string StartDate { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Position Position { get; set; }
    }
}
