//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccount
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income : AccountTransaction
    {
    
        public virtual Loan Loan { get; set; }
        public virtual Mortgage Mortgage { get; set; }
        public virtual Current Current { get; set; }
    }
}
